# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'JKAutoReleaseTimer' do

pod 'JKAutoReleaseTimer', '~> 1.0.0'

end

target 'dev' do
  
  #pod 'JKAutoReleaseTimer', '~> 1.0.0'
  
end
